server:
  port: 8085
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xh_network?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto

oss:
  accessKey: 8pAFyGmTi_oD8e0XouMZ_Pf4yYfL8TFXBa0JFpIN
  secretKey: olC1FCwU1k3gHaNEovQ_85mHMi8hiVkW0xVCvAFG
  bucket: haoge-blog
  filePathTemp: C:\Users\haogebabing\AppData\Local\Temp\java
  filePath: C:\Users\haogebabing\AppData\Local\Temp\java\temp

